import { Raleway, Geist, Geist_Mono } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
// import Header from "@/app/components/Header";
// eslint-disable-next-line @typescript-eslint/no-unused-vars
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// app/layout.tsx

const raleway = Raleway({
  subsets: ["latin"],
  variable: "--font-raleway",
});

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist",
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

export default async function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <ClerkProvider>
      <html
        className={`${raleway.variable} ${geist.variable} ${geistMono.variable}`}
      >
        <body>
          {/* <Header /> */}
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
